### PR TITLE
Add French translations

### PR DESCRIPTION
**Pull request by GautDlpr**

### CODE REVIEW

**Comment by k4yt3x** [comment]
I've added more tooltips to the UI. Do you think you can help translate that as well? If not I'll need to GPT it.

**Comment by GautDlpr** [comment]
Of course, I'd be delighted.
However, I used an existing translation file that I modified.
So if a new translation file or template becomes available, I'll be happy to complete my work.

**Comment by k4yt3x** [comment]
Awesome! I'll update the other translations soon and I'll ping you when they become available. I can also try to update your existing translation file so you'll just have blank fields to fill in.

**Comment by GautDlpr** [comment]
Don't worry about my translation file and just let me know when one of the other files will be updated.

And if you need to update other files with GPT, I can update them with GPT for you if it saves you time.

**Comment by k4yt3x** [comment]
Hi, I've pushed the update and translations for all files. Please take a look when you have time. Thanks again!

**Comment by k4yt3x** [comment]
I know it's quite a bit of new content. I can do it with lupdate and Qt Linguist, so I can do it with GPT if you'd like at any point.

**Comment by GautDlpr** [comment]
Incredible, I'll start later today and try to update my work quickly.

**Comment by k4yt3x** [comment]
Try getting Linguist if you can. Should be much easier than editing XML.

**Comment by GautDlpr** [comment]
Understood I'll try

**Comment by k4yt3x** [comment]
Here's how I manually update the ts files:

```shell
lupdate .\src\ -no-obsolete -ts .\src\video2x-qt6_zh_CN.ts -ts .\src\video2x-qt6_ja_JP.ts -ts .\src\video2x-qt6_pt_PT.ts
```

If you have the full Qt6 environment, you can use lupdate as well, which will auto create the missing fields.

```shell
lupdate .\src\ -no-obsolete -ts .\src\video2x-qt6_fr_FR.ts
```

Unfortunately Qt is making it harder to install these tools :(

**Comment by GautDlpr** [comment]
I'm done, I'll check the file and it'll be fine.

**Comment by GautDlpr** [comment]
Done ! @k4yt3x

**Comment by k4yt3x** [comment]
Great! Merged!
Thanks for the PR.

**Comment by k4yt3x** [comment]
Looking good:

image

image

**Pull request merged**
